version: 2
jobs:
  build:
    working_directory: ~/jsonrpc-bind
    docker:
      -image circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          key: jsonrpc-bind-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save-cache:
          paths:
            - ~/.m2
          key: jsonrpc-bind-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
